//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMApplicationForProjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectsDbContext : DbContext
    {
        public ProjectsDbContext()
            : base("name=ProjectsDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C01_Projects> C01_Projects { get; set; }
        public virtual DbSet<C04_ProjectPhase> C04_ProjectPhase { get; set; }
        public virtual DbSet<C05_BIMtarget> C05_BIMtarget { get; set; }
        public virtual DbSet<C05a_TargetDetail> C05a_TargetDetail { get; set; }
        public virtual DbSet<C02_AppLists> C02_AppLists { get; set; }
        public virtual DbSet<C02a_AppResults> C02a_AppResults { get; set; }
        public virtual DbSet<C02b_AppWorkDetails> C02b_AppWorkDetails { get; set; }
        public virtual DbSet<C03_ProjectAppDetails> C03_ProjectAppDetails { get; set; }
    }
}
