//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMApplicationForProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C01_Projects()
        {
            this.C05a_TargetDetail = new HashSet<C05a_TargetDetail>();
            this.C03_ProjectAppDetails = new HashSet<C03_ProjectAppDetails>();
        }
    
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ARCdesigner { get; set; }
        public Nullable<bool> ARCmakeModel { get; set; }
        public string STRdesigner { get; set; }
        public Nullable<bool> STRmakeModel { get; set; }
        public string MEPdesigner { get; set; }
        public Nullable<bool> MEPmakeModel { get; set; }
        public string CIvilDesigner { get; set; }
        public Nullable<bool> CivilMakeModel { get; set; }
        public string LandscapeDesigner { get; set; }
        public Nullable<bool> LandscapeMakeModel { get; set; }
        public Nullable<int> Phase { get; set; }
        public string BIMtarget { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string PMname { get; set; }
    
        public virtual C04_ProjectPhase C04_ProjectPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C05a_TargetDetail> C05a_TargetDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_ProjectAppDetails> C03_ProjectAppDetails { get; set; }
    }
}
