//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMApplicationForProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_AppLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C02_AppLists()
        {
            this.C02a_AppResults = new HashSet<C02a_AppResults>();
            this.C02b_AppWorkDetails = new HashSet<C02b_AppWorkDetails>();
            this.C03_ProjectAppDetails = new HashSet<C03_ProjectAppDetails>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectPhase { get; set; }
        public string MainImage { get; set; }
        public string SubImage1 { get; set; }
        public string SubImage2 { get; set; }
        public string SubImage3 { get; set; }
        public string SubImage4 { get; set; }
        public string Name_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02a_AppResults> C02a_AppResults { get; set; }
        public virtual C04_ProjectPhase C04_ProjectPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02b_AppWorkDetails> C02b_AppWorkDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_ProjectAppDetails> C03_ProjectAppDetails { get; set; }
    }
}
