//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMApplicationForProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C03_ProjectAppDetails
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public int AppID { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string UserRequest { get; set; }
        public Nullable<bool> isAccept { get; set; }
        public string OtherRequest { get; set; }
        public int StatusID { get; set; }
        public string BIMerName { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> ResultID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string Resource { get; set; }
        public string AppCode { get; set; }
    
        public virtual C01_Projects C01_Projects { get; set; }
        public virtual C02_AppLists C02_AppLists { get; set; }
        public virtual C06_Status C06_Status { get; set; }
        public virtual C07_Result C07_Result { get; set; }
        public virtual C08_RequestType C08_RequestType { get; set; }
    }
}
