//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIMApplicationForProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C99_History
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public int AppID { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
        public string NoiDung { get; set; }
        public string UserChange { get; set; }
        public string Type { get; set; }
    }
}
